### ISSUE TITLE
Oauth dance is not available in Choreo

### ISSUE THREAD

**Issue by SkNuwanTissera** [ballerina-platform/module-ballerinax-googleapis.drive#11]
## Describe your problem(s)
We need to manually initiate the client with Bearer token or Oauth refresh tokens. Oauth dance is not working as in the Gsheets and calendar.
![image](https://user-images.githubusercontent.com/19235998/119124035-d7c21100-ba4d-11eb-9548-46004ab21b4d.png)

## Describe your solution(s)
Enable OAuth dance for Google drive 
![image](https://user-images.githubusercontent.com/19235998/119208535-37590480-bac0-11eb-8a29-da8d6feb4755.png)

**Comment by SkNuwanTissera** [comment]
This feature is on hold

**Comment by abeykoon** [comment]
We decided to drop this support. So issue is not valid anymore.
